DECLARE 

BEGIN

for rec in ( select r.CNTRY,r.CNTY from RCVR_RGN r group by r.CNTRY,r.CNTY order by  r.CNTY asc) loop
  INSERT INTO CNTY(CNTY_ID,CNTY_NAM,CNTY_CPTL,HNTR_PPLTN,HS_STATE,MAP_DTS,CNTRY_ID,CNTY_CDE,CRET_DATE,LST_UPDT_DATE,CRTD_BY,LST_UPDTD_BY)
  VALUES( ( SELECT NVL(MAX(CNTY_ID)+1, 1) FROM  CNTY),rec.CNTY,NULL,0,'N',NULL,1,254,SYSDATE,SYSDATE,'admin','admin' );
end loop;

END;

