package com.techmaster.hunter.email;

import java.util.Map;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;

import com.techmaster.hunter.obj.beans.HunterEmailTemplateBean;
import com.techmaster.hunter.obj.beans.Task;

public class TaskEmailManagerImpl extends AbstractEmailManager{

	@Autowired private JavaMailSender javaMailSender;
	@Autowired private SimpleMailMessage templateMessage;
	private Logger logger = Logger.getLogger(TaskEmailManagerImpl.class);
	
	public void setJavaMailSender(JavaMailSender javaMailSender) {
        this.javaMailSender = javaMailSender;
    }
    public void setTemplateMessage(SimpleMailMessage templateMessage) {
        this.templateMessage = templateMessage;
    }
	
    
    @Override
	public void send(Task task, String mailType) throws MessagingException {
    	
    	MimeMessage mimeMsg = this.javaMailSender.createMimeMessage();
    	MimeMessageHelper helper = new MimeMessageHelper(mimeMsg, true);
    	helper.setTo("hklangats@gmail.com");
    	helper.addTo("hillangat@gmail.com");
    	helper.addTo("tclangat@gmail.com");
    	helper.addTo("techmaster.hunter.mail@gmail.com");
    	helper.setFrom("techmaster.hunter.mail@gmail.com"); 
    	helper.setSubject("Techmaster Hunter Email Testing"); 
    	String htmlMsg = "<html><body><div style='color:#051F0E;with:50%;-webkit-box-shadow: 0 0 5px 2px #E2F3FF;padding:10px;background-color:#EBFAFF;margin-left:2%;border:1px solid #3570AC;border-radius:4px;height:20px;' >Hi Theresa!! <br/> Merry Christmass And Happy New Year!!<br/>"
    			+ "<br/>This email is autogenerated.<br/> Please do not reply."
    			+ "</div></body></html>";
    	mimeMsg.setContent(htmlMsg, "text/html");
    	this.javaMailSender.send(mimeMsg); 
    	
	}
    
	@Override
	public MimeMessageHelper getMimeMsgHelperForMailType(String mailType,HunterEmailTemplateBean hunterEmailTemplateBean,Map<String, Object> cntntParams) {
		// TODO Auto-generated method stub
		return null;
	}
	
    
    
    
}
